<a href="https://colab.research.google.com/github/umesh03B/ma22c048_2023_PL/blob/main/Assignment/Assignment_6/Pairwise_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

x = np.random.rand(5) #generates a 1D NumPy array x of length 5 filled with random numbers between 0 and 1 using the np.random.rand function.

D = np.subtract.outer(x, x)  #np.subtract.outer(x, x) will be a 2D array where each element at position [i][j] represents the result of subtracting x[i] from x[j].
print(D)

[[ 0.         -0.00360581 -0.19451765 -0.20489685 -0.10533089]
 [ 0.00360581  0.         -0.19091185 -0.20129104 -0.10172508]
 [ 0.19451765  0.19091185  0.         -0.0103792   0.08918677]
 [ 0.20489685  0.20129104  0.0103792   0.          0.09956596]
 [ 0.10533089  0.10172508 -0.08918677 -0.09956596  0.        ]]


In [ ]:
#extanded version
A = np.zeros((5,5))
for i in range(5):
  for j in range (5):
    A[i][j]=x[i]-x[j]

print(A)

[[ 0.         -0.00360581 -0.19451765 -0.20489685 -0.10533089]
 [ 0.00360581  0.         -0.19091185 -0.20129104 -0.10172508]
 [ 0.19451765  0.19091185  0.         -0.0103792   0.08918677]
 [ 0.20489685  0.20129104  0.0103792   0.          0.09956596]
 [ 0.10533089  0.10172508 -0.08918677 -0.09956596  0.        ]]
