<a href="https://colab.research.google.com/github/umesh03B/ma22c048_2023_PL/blob/main/Assignment/Assignment_8/Column_space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.linalg import qr,svd


In [3]:
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

In [8]:
# SVD
u, s, vT = svd(A)
print("SVD U Matrix:")
print(u)
print("SVD U Transpose:")
print(u.T)

SVD U Matrix:
[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]]
SVD U Transpose:
[[ 2.66235859e-01  5.39615303e-01 -7.98707576e-01]
 [ 1.70641342e-01 -8.41911709e-01 -5.11924025e-01]
 [ 9.48683298e-01 -5.55111512e-17  3.16227766e-01]]


In [9]:
# QR factorization
q, r = qr(A)
print("QR Q Matrix:")
print(q)
print("QR R Matrix:")
print(r)

QR Q Matrix:
[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]
QR R Matrix:
[[-3.74165739e+00  7.48331477e+00 -1.28285396e+01  9.08688223e+00]
 [ 0.00000000e+00 -1.98602732e-15 -1.31705767e-01 -1.75607689e-01]
 [ 0.00000000e+00  0.00000000e+00  2.53203970e+00  3.37605293e+00]]


In [10]:
# Task 2: Verify if the basis from SVD and QR can generate the same vector space
aug_uq = np.vstack((u, q.T))
print("Augmented Matrix [u, q.T]:")
print(aug_uq)

rank_aug_uq = np.linalg.matrix_rank(aug_uq)
rank_u = np.linalg.matrix_rank(u)
rank_q = np.linalg.matrix_rank(q)

print("Rank of [u, q.T]:", rank_aug_uq)
print("Rank of u:", rank_u)
print("Rank of q:", rank_q)

Augmented Matrix [u, q.T]:
[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]
 [-2.67261242e-01 -5.34522484e-01  8.01783726e-01]
 [ 9.56182887e-01 -4.39019222e-02  2.89459681e-01]
 [-1.19522861e-01  8.44013232e-01  5.22834534e-01]]
Rank of [u, q.T]: 3
Rank of u: 3
Rank of q: 3


In [11]:
if rank_aug_uq == rank_u == rank_q:
    print("Both bases can generate the same column space.")

Both bases can generate the same column space.


In [12]:
# Task 3: Compare the execution time of SVD and QR on random matrices
B = np.random.rand(500, 500)

print("\nComparing execution time of SVD and QR on a random 500x500 matrix:")

# Measure the execution time for SVD
%timeit U, S, VT = svd(B)

# Measure the execution time for QR
%timeit Q, R = qr(B)


Comparing execution time of SVD and QR on a random 500x500 matrix:
138 ms ± 33.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
29.2 ms ± 874 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
