<a href="https://colab.research.google.com/github/umesh03B/ma22c048_2023_PL/blob/main/Assignment%20/Assignment_5/Row_swap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def given_swap_row(i, j, A):
    tmp = A[i, :] #velue of tmp='i'th row of A
    A[i, :] = A[j, :] # velue of 'i'th row changed new velue of 'i'th row = 'j'th row of A so velue of tmp is also changed so new value of tmp = velue of 'j'th row of orignal matrix
    A[j, :] = tmp # value of 'j'th row changed buy tmp which is 'j'th row of orignal matrix
    return A      # so after interchanging 'i'th and 'j'th row we get the metrix whose 'i'th and 'j'th row are same (i.e 'j'th row of orignal matrix)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Call given_swap_row() to interchange rows 0 and 2 (first and last rows)
result = given_swap_row(0, 2, A)

# Print the result
print(result)



[[7 8 9]
 [4 5 6]
 [7 8 9]]


so there is a problem in given code

In [ ]:
def modifide_swap_rows(i, j, A):
    """
    Swap rows i and j in a numpy array A.

    Parameters:
    - i: Index of the first row to swap.
    - j: Index of the second row to swap.
    - A: The numpy array in which rows will be swapped.

    Returns:
    - A: The numpy array with rows i and j swapped.
    """

    # Check if i and j are valid row indices
    if i < 0 or i >= len(A) or j < 0 or j >=len(A):
        print("Invalid row indices.")
    else:
        tmp = A[i, :].copy()  # Make a copy of the row so that velue of tmp not change if we change velue of A[i,:]
        A[i, :] = A[j, :]
        A[j, :] = tmp
        return A

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Call modifide_swap_rows() to interchange rows 0 and 2 (first and last rows)
result = modifide_swap_rows(0, 2, A)

# Print the result
print(result)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


NumPy arrays are mutable objects, and when you assign one array to another variable, you are essentially creating a reference to the same underlying data. Without .copy(), both tmp and A[i, :] would refer to the same row in memory.
By using .copy(), you create a new copy of the row in tmp, ensuring that the original values of A[i, :] are preserved, and the swap works as expected.